### ISSUE TITLE
how to tranform 3d points from one frame to another

### ISSUE THREAD

**Issue by hughlee815** [gdlg/simple-waymo-open-dataset-reader#12]
hi,
gdlg,
thanks for your awesome work. may i ask a question about the transformation? how can man tranform 3d points from one frame to another(or is it even possible to do that?)
i know there is a 4x4 row major transform matrix. but it is 4x4. when we have points whose shape is (n, 3), how can we do the transform operation?
thanks for your reply in advance.

**Comment by gdlg** [comment]
Hi @hughlee815 ,

I would suggest that you read about transformation matrices and homogeneous coordinates in 2D & 3D, they are very common in computer vision and computer graphics because those matrices can represent any affine transformation of the 3D space (such as a change of frame). For instance:
https://medium.com/swlh/understanding-3d-matrix-transforms-with-pixijs-c76da3f8bd8

**Comment by hughlee815** [comment]
That's cool. this helps me a lot. Thanks so much for your advice.
